# Generated by Django 4.2.7 on 2023-11-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('attribute', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
