# Generated by Django 4.2.7 on 2023-11-23 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh_api', '0002_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yugioh_api.card')),
            ],
        ),
    ]
