# Generated by Django 4.2.7 on 2023-11-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh_api', '0004_alter_cardprice_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprice',
            name='min_price',
            field=models.FloatField(),
        ),
    ]
